"""
--- Part Two ---
For some reason, your simulated results don't match what the experimental energy source engineers expected. Apparently, the pocket dimension actually has four spatial dimensions, not three.

The pocket dimension contains an infinite 4-dimensional grid. At every integer 4-dimensional coordinate (x,y,z,w), there exists a single cube (really, a hypercube) which is still either active or inactive.

Each cube only ever considers its neighbors: any of the 80 other cubes where any of their coordinates differ by at most 1. For example, given the cube at x=1,y=2,z=3,w=4, its neighbors include the cube at x=2,y=2,z=3,w=3, the cube at x=0,y=2,z=3,w=4, and so on.

The initial state of the pocket dimension still consists of a small flat region of cubes. Furthermore, the same rules for cycle updating still apply: during each cycle, consider the number of active neighbors of each cube.

For example, consider the same initial state as in the example above. Even though the pocket dimension is 4-dimensional, this initial state represents a small 2-dimensional slice of it. (In particular, this initial state defines a 3x3x1x1 region of the 4-dimensional space.)

Simulating a few cycles from this initial state produces the following configurations, where the result of each cycle is shown layer-by-layer at each given z and w coordinate:

    Before any cycles:

        z=0, w=0
        .#.
        ..#
        ###


        After 1 cycle:

            z=-1, w=-1
            #..
            ..#
            .#.

            z=0, w=-1
            #..
            ..#
            .#.

            z=1, w=-1
            #..
            ..#
            .#.

            z=-1, w=0
            #..
            ..#
            .#.

            z=0, w=0
            #.#
            .##
            .#.

            z=1, w=0
            #..
            ..#
            .#.

            z=-1, w=1
            #..
            ..#
            .#.

            z=0, w=1
            #..
            ..#
            .#.

            z=1, w=1
            #..
            ..#
            .#.


            After 2 cycles:

                z=-2, w=-2
                .....
                .....
                ..#..
                .....
                .....

                z=-1, w=-2
                .....
                .....
                .....
                .....
                .....

                z=0, w=-2
                ###..
                ##.##
                #...#
                .#..#
                .###.

                z=1, w=-2
                .....
                .....
                .....
                .....
                .....

                z=2, w=-2
                .....
                .....
                ..#..
                .....
                .....

                z=-2, w=-1
                .....
                .....
                .....
                .....
                .....

                z=-1, w=-1
                .....
                .....
                .....
                .....
                .....

                z=0, w=-1
                .....
                .....
                .....
                .....
                .....

                z=1, w=-1
                .....
                .....
                .....
                .....
                .....

                z=2, w=-1
                .....
                .....
                .....
                .....
                .....

                z=-2, w=0
                ###..
                ##.##
                #...#
                .#..#
                .###.

                z=-1, w=0
                .....
                .....
                .....
                .....
                .....

                z=0, w=0
                .....
                .....
                .....
                .....
                .....

                z=1, w=0
                .....
                .....
                .....
                .....
                .....

                z=2, w=0
                ###..
                ##.##
                #...#
                .#..#
                .###.

                z=-2, w=1
                .....
                .....
                .....
                .....
                .....

                z=-1, w=1
                .....
                .....
                .....
                .....
                .....

                z=0, w=1
                .....
                .....
                .....
                .....
                .....

                z=1, w=1
                .....
                .....
                .....
                .....
                .....

                z=2, w=1
                .....
                .....
                .....
                .....
                .....

                z=-2, w=2
                .....
                .....
                ..#..
                .....
                .....

                z=-1, w=2
                .....
                .....
                .....
                .....
                .....

                z=0, w=2
                ###..
                ##.##
                #...#
                .#..#
                .###.

                z=1, w=2
                .....
                .....
                .....
                .....
                .....

                z=2, w=2
                .....
                .....
                ..#..
                .....
                .....
                After the full six-cycle boot process completes, 848 cubes are left in the active state.

                Starting with your given initial configuration, simulate six cycles in a 4-dimensional space. How many cubes are left in the active state after the sixth cycle?
"""

import copy

CYCLES = 6

def solve(data):
    minh, maxh = -1, len(data) + 1
    minw, maxw = -1, len(data[0]) + 1
    mind, maxd = -1, 1 + 1
    mint, maxt = -1, 1 + 1

    cubes = {}
    for i in range(minh, maxh + 1):
        for j in range(minw, maxw + 1):
            for k in range(mind, maxd + 1):
                for l in range(mint, maxt + 1):
                    cubes[(i, j, k, l)] = data[i][j] if i in range(0, len(data)) and j in range(0, len(data[0])) and k == 0 and l == 0 else "."

    for cycle in range(CYCLES):
        cp = copy.deepcopy(cubes)
        for i in range(minh - 1, maxh + 2):
            for j in range(minw - 1, maxw + 2):
                for k in range(mind - 1, maxd + 2):
                    for l in range(mint - 1, maxt + 2):
                        changed = False
                        active_count = 0
                        for a in [-1, 0, 1]:
                            for b in [-1, 0, 1]:
                                for c in [-1, 0, 1]:
                                    for d in [-1, 0, 1]:
                                        if a == 0 and b == 0 and c == 0 and d == 0:
                                            continue
                                        i_, j_, k_, l_ = i + a, j + b, k + c, l + d
                                        if (i_, j_, k_, l_) in cubes and cubes[(i_, j_, k_, l_)] == "#":
                                            active_count += 1
                        if cubes.get((i, j, k, l), ".") == "." and active_count == 3:
                            cp[(i, j, k, l)] = "#"
                            changed = True
                        elif cubes.get((i, j, k, l), ".") == "#" and active_count not in [2, 3]:
                            cp[(i, j, k, l)] = "."
                            changed = True
                        if changed:
                            minh = min(minh, i)
                            maxh = max(maxh, i)
                            minw = min(minw, j)
                            maxw = max(maxw, j)
                            mind = min(mind, k)
                            maxd = max(maxd, k)
                            mint = min(mint, k)
                            maxt = max(maxt, k)
        cubes = copy.deepcopy(cp)

    num_active = 0
    for i in range(minh - 1, maxh + 1):
        for j in range(minw - 1, maxw + 1):
            for k in range(mind - 1, maxd + 1):
                for l in range(mint - 1, maxt + 1):
                    if cubes.get((i, j, k, l), ".") == "#":
                        num_active += 1
    return num_active

def main():
    with open("input/17.txt") as f:
        data = []
        for line in f:
            data.append(list(line.strip()))
        print(solve(data))

if __name__ == "__main__":
    main()
